In [30]:
import pandas

读入相关数据表，然后查看每行所代表的具体内容
---

In [31]:
data=pandas.read_csv('../data/data.csv',encoding='gbk')
data.head(5)

,Unnamed: 0,custid,trade_no,bank_card_no,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,5,2791858,20180507115231274000000023057383,卡号1,0.01,0.99,0,0.90,0.55,0.313,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,10,534047,20180507121002192000000023073000,卡号1,0.02,0.94,2000,1.28,1.00,0.458,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,12,2849787,20180507125159718000000023114911,卡号1,0.04,0.96,0,1.00,1.00,0.114,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,13,1809708,20180507121358683000000388283484,卡号1,0.00,0.96,2000,0.13,0.57,0.777,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,14,2499829,20180507115448545000000388205844,卡号1,0.01,0.99,0,0.46,1.00,0.175,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0

**查看数据的大致信息，并且进行简单分析**

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4754 entries, 0 to 4753
Data columns (total 90 columns):
Unnamed: 0                                    4754 non-null int64
custid                                        4754 non-null int64
trade_no                                      4754 non-null object
bank_card_no                                  4754 non-null object
low_volume_percent                            4752 non-null float64
middle_volume_percent                         4752 non-null float64
take_amount_in_later_12_month_highest         4754 non-null int64
trans_amount_increase_rate_lately             4751 non-null float64
trans_activity_month                          4752 non-null float64
trans_activity_day                            4752 non-null float64
transd_mcc                                    4752 non-null float64
trans_days_interval_filter                    4746 non-null float64
trans_days_interval                           4752 non-null float64
regional_mobility                             4752 non-null float64
student_feature                               1756 non-null float64
repayment_capability                          4754 non-null int64
is_high_user                                  4754 non-null int64
number_of_trans_from_2011                     4752 non-null float64
first_transaction_time                        4752 non-null float64
historical_trans_amount                       4754 non-null int64
historical_trans_day                          4752 non-null float64
rank_trad_1_month                             4752 non-null float64
trans_amount_3_month                          4754 non-null int64
avg_consume_less_12_valid_month               4752 non-null float64
abs                                           4754 non-null int64
top_trans_count_last_1_month                  4752 non-null float64
avg_price_last_12_month                       4754 non-null int64
avg_price_top_last_12_valid_month             4650 non-null float64
reg_preference_for_trad                       4752 non-null object
trans_top_time_last_1_month                   4746 non-null float64
trans_top_time_last_6_month                   4746 non-null float64
consume_top_time_last_1_month                 4746 non-null float64
consume_top_time_last_6_month                 4746 non-null float64
cross_consume_count_last_1_month              4328 non-null float64
trans_fail_top_count_enum_last_1_month        4738 non-null float64
trans_fail_top_count_enum_last_6_month        4738 non-null float64
trans_fail_top_count_enum_last_12_month       4738 non-null float64
consume_mini_time_last_1_month                4728 non-null float64
max_cumulative_consume_later_1_month          4754 non-null int64
max_consume_count_later_6_month               4746 non-null float64
railway_consume_count_last_12_month           4742 non-null float64
pawns_auctions_trusts_consume_last_1_month    4754 non-null int64
pawns_auctions_trusts_consume_last_6_month    4754 non-null int64
jewelry_consume_count_last_6_month            4742 non-null float64
status                                        4754 non-null int64
source                                        4754 non-null object
first_transaction_day                         4752 non-null float64
trans_day_last_12_month                       4752 non-null float64
id_name                                       4478 non-null object
apply_score                                   4450 non-null float64
apply_credibility                             4450 non-null float64
query_org_count                               4450 non-null float64
query_finance_count                           4450 non-null float64
query_cash_count                              4450 non-null float64
query_sum_count                               4450 non-null float64
latest_query_time                             4450 non-null object
latest_one_month_apply                        4450 non-null float64
latest_three_month_apply                      4450 non-null float64
latest_six_month_apply                        4450 non-null float64
loans_score                                   4457 non-null float64
loans_credibility_behavior                    4457 non-null float64
loans_count                                   4457 non-null float64
loans_settle_count                            4457 non-null float64
loans_overdue_count                           4457 non-null float64
loans_org_count_behavior                      4457 non-null float64
consfin_org_count_behavior                    4457 non-null float64
loans_cash_count                              4457 non-null float64
latest_one_month_loan                         4457 non-null float64
latest_three_month_loan                       4457 non-null float64
latest_six_month_loan                         4457 non-null float64
history_suc_fee                               4457 non-null float64
history_fail_fee                              4457 non-null float64
latest_one_month_suc                          4457 non-null float64
latest_one_month_fail                         4457 non-null float64
loans_long_time                               4457 non-null float64
loans_latest_time                             4457 non-null object
loans_credit_limit                            4457 non-null float64
loans_credibility_limit                       4457 non-null float64
loans_org_count_current                       4457 non-null float64
loans_product_count                           4457 non-null float64
loans_max_limit                               4457 non-null float64
loans_avg_limit                               4457 non-null float64
consfin_credit_limit                          4457 non-null float64
consfin_credibility                           4457 non-null float64
consfin_org_count_current                     4457 non-null float64
consfin_product_count                         4457 non-null float64
consfin_max_limit                             4457 non-null float64
consfin_avg_limit                             4457 non-null float64
latest_query_day                              4450 non-null float64
loans_latest_day                              4457 non-null float64
dtypes: float64(70), int64(13), object(7)
memory usage: 3.3+ MB

**简单分析**  
查看上面的数据可知，总共是有4754行，然后总共分为90列
经过粗略的观察，发现student_feature这一列的内容与其他的不是很相同，它只有1756 non-null float64，即这一列存在大量的缺失值，后期处理的时候
需要特别注意（或者是直接删除）。另外也存在一些列存在缺失值，后面建模的时候要处理
数据类型部分：
在这个data里面，数据类型分为三种，即：float64,int64,以及object这三种数据类型，在建模的时候需要将objetc类型进行转换

In [33]:
# 查看数据的属性
for i,name in enumerate(data.columns):
    name_sum = data[name].value_counts().shape[0]
    print("{:2}、{:50} The number of types of features is：{}"
          .format(i+1, name, name_sum))

 1、Unnamed: 0                                         The number of types of features is：4754
 2、custid                                             The number of types of features is：4754
 3、trade_no                                           The number of types of features is：4754
 4、bank_card_no                                       The number of types of features is：1
 5、low_volume_percent                                 The number of types of features is：40
 6、middle_volume_percent                              The number of types of features is：90
 7、take_amount_in_later_12_month_highest              The number of types of features is：166
 8、trans_amount_increase_rate_lately                  The number of types of features is：782
 9、trans_activity_month                               The number of types of features is：84
10、trans_activity_day                                 The number of types of features is：512
11、transd_mcc                                         The number of types of features is：41
12、trans_days_interval_filter                         The number of types of features is：147
13、trans_days_interval                                The number of types of features is：114
14、regional_mobility                                  The number of types of features is：5
15、student_feature                                    The number of types of features is：2
16、repayment_capability                               The number of types of features is：2390
17、is_high_user                                       The number of types of features is：2
18、number_of_trans_from_2011                          The number of types of features is：70
19、first_transaction_time                             The number of types of features is：1693
20、historical_trans_amount                            The number of types of features is：4524
21、historical_trans_day                               The number of types of features is：476
22、rank_trad_1_month                                  The number of types of features is：20
23、trans_amount_3_month                               The number of types of features is：3524
24、avg_consume_less_12_valid_month                    The number of types of features is：12
25、abs                                                The number of types of features is：1697
26、top_trans_count_last_1_month                       The number of types of features is：8
27、avg_price_last_12_month                            The number of types of features is：330
28、avg_price_top_last_12_valid_month                  The number of types of features is：20
29、reg_preference_for_trad                            The number of types of features is：5
30、trans_top_time_last_1_month                        The number of types of features is：28
31、trans_top_time_last_6_month                        The number of types of features is：97
32、consume_top_time_last_1_month                      The number of types of features is：28
33、consume_top_time_last_6_month                      The number of types of features is：94
34、cross_consume_count_last_1_month                   The number of types of features is：19
35、trans_fail_top_count_enum_last_1_month             The number of types of features is：15
36、trans_fail_top_count_enum_last_6_month             The number of types of features is：25
37、trans_fail_top_count_enum_last_12_month            The number of types of features is：26
38、consume_mini_time_last_1_month                     The number of types of features is：1971
39、max_cumulative_consume_later_1_month               The number of types of features is：863
40、max_consume_count_later_6_month                    The number of types of features is：29
41、railway_consume_count_last_12_month                The number of types of features is：6
42、pawns_auctions_trusts_consume_last_1_month         The number of types of features is：572
43、pawns_auctions_trusts_consume_last_6_month         The number of types of features is：2730
44、jewelry_consume_count_last_6_month                 The number of types of features is：7
45、status                                             The number of types of features is：2
46、source                                             The number of types of features is：1
47、first_transaction_day                              The number of types of features is：1693
48、trans_day_last_12_month                            The number of types of features is：132
49、id_name                                            The number of types of features is：4309
50、apply_score                                        The number of types of features is：205
51、apply_credibility                                  The number of types of features is：41
52、query_org_count                                    The number of types of features is：46
53、query_finance_count                                The number of types of features is：25
54、query_cash_count                                   The number of types of features is：17
55、query_sum_count                                    The number of types of features is：74
56、latest_query_time                                  The number of types of features is：207
57、latest_one_month_apply                             The number of types of features is：36
58、latest_three_month_apply                           The number of types of features is：56
59、latest_six_month_apply                             The number of types of features is：65
60、loans_score                                        The number of types of features is：247
61、loans_credibility_behavior                         The number of types of features is：25
62、loans_count                                        The number of types of features is：134
63、loans_settle_count                                 The number of types of features is：123
64、loans_overdue_count                                The number of types of features is：26
65、loans_org_count_behavior                           The number of types of features is：41
66、consfin_org_count_behavior                         The number of types of features is：19
67、loans_cash_count                                   The number of types of features is：32
68、latest_one_month_loan                              The number of types of features is：14
69、latest_three_month_loan                            The number of types of features is：31
70、latest_six_month_loan                              The number of types of features is：67
71、history_suc_fee                                    The number of types of features is：171
72、history_fail_fee                                   The number of types of features is：151
73、latest_one_month_suc                               The number of types of features is：19
74、latest_one_month_fail                              The number of types of features is：41
75、loans_long_time                                    The number of types of features is：202
76、loans_latest_time                                  The number of types of features is：232
77、loans_credit_limit                                 The number of types of features is：54
78、loans_credibility_limit                            The number of types of features is：33
79、loans_org_count_current                            The number of types of features is：32
80、loans_product_count                                The number of types of features is：32
81、loans_max_limit                                    The number of types of features is：91
82、loans_avg_limit                                    The number of types of features is：961
83、consfin_credit_limit                               The number of types of features is：327
84、consfin_credibility                                The number of types of features is：24
85、consfin_org_count_current                          The number of types of features is：19
86、consfin_product_count                              The number of types of features is：20
87、consfin_max_limit                                  The number of types of features is：175
88、consfin_avg_limit                                  The number of types of features is：1677
89、latest_query_day                                   The number of types of features is：210
90、loans_latest_day                                   The number of types of features is：235

In [34]:
# 数据描述
data.describe()

,Unnamed: 0,custid,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
count,4754.000000,4.754000e+03,4752.000000,4752.000000,4754.000000,4751.000000,4752.000000,4752.000000,4752.000000,4746.000000,...,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4450.000000,4457.000000
mean,6008.414178,1.690993e+06,0.021806,0.901294,1940.197728,14.160674,0.804411,0.365425,17.502946,29.029920,...,3390.038142,1820.357864,9187.009199,76.042630,4.732331,5.227507,16153.690823,8007.696881,24.112809,55.181512
std,3452.071428,1.034235e+06,0.041527,0.144856,3923.971494,694.180473,0.196920,0.170196,4.475616,22.722432,...,1474.206546,583.418291,7371.257043,14.536819,2.974596,3.409292,14301.037628,5679.418585,37.725724,53.486408
min,5.000000,1.140000e+02,0.000000,0.000000,0.000000,0.000000,0.120000,0.033000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.000000,-2.000000
25%,3106.000000,7.593358e+05,0.010000,0.880000,0.000000,0.615000,0.670000,0.233000,15.000000,16.000000,...,2300.000000,1535.000000,4800.000000,77.000000,2.000000,3.000000,7800.000000,4737.000000,5.000000,10.000000
50%,6006.500000,1.634942e+06,0.010000,0.960000,500.000000,0.970000,0.860000,0.350000,17.000000,23.000000,...,3100.000000,1810.000000,7700.000000,79.000000,4.000000,5.000000,13800.000000,7050.000000,14.000000,36.000000
75%,8999.000000,2.597905e+06,0.020000,0.990000,2000.000000,1.600000,1.000000,0.480000,20.000000,32.000000,...,4300.000000,2100.000000,11700.000000,80.000000,7.000000,7.000000,20400.000000,10000.000000,24.000000,91.000000
max,11992.000000,4.004694e+06,1.000000,1.000000,68000.000000,47596.740000,1.000000,0.941000,42.000000,285.000000,...,10000.000000,6900.000000,87100.000000,87.000000,18.000000,20.000000,266400.000000,82800.000000,360.000000,323.000000

**describe分析**  
首先，这是统计出来了83列的信息，即数据中object类型存在7列（不能用计数、均值等等去描述），然后在前面可知：int64 共有13列，float64 共有70列
然后更深层次的信息分析：  
大部分数据特征存在拖尾现象， 即特征的 max(min) 明显偏离其 mean ，需要对这些数据进行进一步的处理才能建立准确的模型。
再是结合上面的名称以及在表中均值方差的特点，可以看到部分列的数据类型存在问题，如'first_transaction_time'是data类型而不是float64 类型

无关特征的删除
----
分析data，有些数据对于建立模型是没有任何用处的,可以结合一下具体的贷款场景以及上面中的number of feature
- Unnamed: 0'
- 客户id：'custid'
- 流水号：'trade_no'
- 卡号：'bank_card_no'
- 资源：'source'
- 客户姓名：'id_name'
- 最新查询时间：'latest_query_time'
- 最新贷款时间：'loans_latest_time'  
这些特征也可以进行删除

In [35]:
data=data.drop(['Unnamed: 0','custid','trade_no','source','id_name','latest_query_time','loans_latest_time','bank_card_no'],axis=1)

In [37]:
# 删除了8列之后的数据变成了下面这样的形式
data.head(5)

,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,trans_days_interval,regional_mobility,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,0.01,0.99,0,0.90,0.55,0.313,17.0,27.0,26.0,3.0,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,0.02,0.94,2000,1.28,1.00,0.458,19.0,30.0,14.0,4.0,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,0.04,0.96,0,1.00,1.00,0.114,13.0,68.0,22.0,1.0,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,0.00,0.96,2000,0.13,0.57,0.777,22.0,14.0,6.0,3.0,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,0.01,0.99,0,0.46,1.00,0.175,13.0,66.0,42.0,1.0,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0

数据类型的转换
---
在前面的分析中可知，部分的列的数据类型与实际的数据类型不符合，另外，不是所有的数据类型都是数值类型，需要先转换为数值类型

In [38]:
data.reg_preference_for_trad.unique()

array(['一线城市', '三线城市', '境外', '二线城市', '其他城市', nan], dtype=object)

In [39]:
# 数据类型进行转换，将其进行映射
for i in range(0, data.shape[0]):
    if data.reg_preference_for_trad[i] == '一线城市':
        data.reg_preference_for_trad[i] = 1
    elif data.reg_preference_for_trad[i] == '二线城市':
        data.reg_preference_for_trad[i] = 2
    elif data.reg_preference_for_trad[i] == '三线城市':
        data.reg_preference_for_trad[i] = 3
    elif data.reg_preference_for_trad[i] == '境外':
        data.reg_preference_for_trad[i] = 4
    elif data.reg_preference_for_trad[i] == '其他城市':
        data.reg_preference_for_trad[i] = 5

J:\python\env\nlp\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
J:\python\env\nlp\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

J:\python\env\nlp\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
J:\python\env\nlp\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

J:\python\env\nlp\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [40]:
# 将其他的object类型进行转换

data = data.convert_objects(convert_numeric=True)
data.dtypes.value_counts()

J:\python\env\nlp\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  This is separate from the ipykernel package so we can avoid doing imports until

float64    71
int64      11
dtype: int64

缺失值处理
----
在这里，主要是学习缺失值的处理规则，什么样的列中缺失值应该丢弃，什么样的缺失值应该进行填补，采用什么方式进行填补
【PS】有的可以采用简单的用均值进行填充，用最大值、最小值进行填充，同样的，现在也是可以对某个值采用更加精细的，使用机器学习方法如决策树来进行填充缺失值  
- 删除缺失值较多的行列  
  若某个特征的缺失值超过 30%，那么它会损失特征的关键信息。  
  同样若某个样本的缺失值过多，那么它也不再具有统计学意义。  

因此我们对这样的行或列直接进行删除。

In [41]:
data = data.dropna(axis=1, thresh = 1000)#删除缺失值超过 70% 的列
data = data.dropna(axis=0, thresh = 75)#删除缺失值超过7个的行

- 填充缺失值

对于剩余的缺失值，这里采用 平均值填充法 进行填充。

In [43]:
# 注意代码编写方式
data = data.fillna(data.mean())
data.head()

,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,trans_days_interval,regional_mobility,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,0.01,0.99,0,0.90,0.55,0.313,17.0,27.0,26.0,3.0,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,0.02,0.94,2000,1.28,1.00,0.458,19.0,30.0,14.0,4.0,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,0.04,0.96,0,1.00,1.00,0.114,13.0,68.0,22.0,1.0,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,0.00,0.96,2000,0.13,0.57,0.777,22.0,14.0,6.0,3.0,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,0.01,0.99,0,0.46,1.00,0.175,13.0,66.0,42.0,1.0,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0

数据集切分
----
对于数据集切分，我们可以直接进行切分，也可以借助于sklearn进行处理

In [48]:
# 采用基础的方法进行切分数据集,
from sklearn.utils import shuffle
data=shuffle(data)

train_data_len=int(len(data)*0.7)
train_data=data[:train_data_len]
test_data=data[train_data_len+1:]

In [49]:
# 直接采用sklearn 里面的包来进行训练集、测试集切分
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(data, test_size=0.3, random_state=2018)

In [50]:
# 将训练集和测试集的数据进行保存
train_data.to_csv('../data/train_data.csv', index=False, header=True)
test_data.to_csv('../data/test_data.csv', index=False, header=True)